import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

import { getIAMConfig } from '@auth/iam.js';
import {
  getStorageConfig,
  getTigrisConfig,
  resolveAuthMethod,
} from '@auth/provider.js';
import { assignBucketRoles, createAccessKey } from '@tigrisdata/iam';
import type { BucketLocations } from '@tigrisdata/storage';
import { createBucket, removeBucket } from '@tigrisdata/storage';
import { failWithError, printNextActions } from '@utils/exit.js';
import { parseLocations } from '@utils/locations.js';
import { msg, printStart, printSuccess } from '@utils/messages.js';
import { getFormat, getOption } from '@utils/options.js';
import {
  adjectives,
  animals,
  colors,
  uniqueNamesGenerator,
} from 'unique-names-generator';

import { oauth } from '../login/oauth.js';
import { setupAgentResources } from './agent-setup.js';
import { installProjectPackages } from './packages.js';

const context = msg('project', 'setup');

export default async function setup(options: Record<string, unknown>) {
  printStart(context);

  const format = getFormat(options);

  const bucketOverride = getOption<string>(options, ['bucket', 'b']);
  const access = getOption<string>(options, ['access', 'a']) ?? 'private';
  const locations = getOption<string>(options, ['locations', 'l']) ?? 'global';
  const envFileOpt =
    getOption<string>(options, ['env-file', 'envFile']) ?? '.env';
  const force = getOption<boolean>(options, ['force']) === true;
  const skipAgentSetup =
    getOption<boolean>(options, ['skip-agent-setup', 'skipAgentSetup']) ===
    true;
  const skipInstall =
    getOption<boolean>(options, ['skip-install', 'skipInstall']) === true;

  if (access !== 'private' && access !== 'public') {
    failWithError(
      context,
      `Invalid access level "${access}". Use private or public.`
    );
  }

  // Validate locations early so we fail before creating anything.
  let parsedLocations: BucketLocations;
  try {
    parsedLocations = parseLocations(locations);
  } catch (err) {
    return failWithError(context, err);
  }

  // Detect an existing .env early — if the project is already set up, abort
  // before touching the account.
  const envPath = resolve(process.cwd(), envFileOpt);
  if (existsSync(envPath) && !force) {
    failWithError(
      context,
      `A .env file already exists at ${envPath}.\nThis project looks already set up — use --force to overwrite it.`
    );
  }

  // Ensure the user is authenticated. When no auth is configured, pop the
  // browser via the OAuth device flow.
  const method = await resolveAuthMethod();
  if (method.type === 'none') {
    await oauth();
  }

  const bucketName =
    bucketOverride ??
    uniqueNamesGenerator({
      dictionaries: [colors, adjectives, animals],
      separator: '-',
      length: 3,
    });

  // 1. Create the bucket.
  const { error: bucketError } = await createBucket(bucketName, {
    access,
    locations: parsedLocations,
    config: await getStorageConfig(),
  });
  if (bucketError) {
    failWithError(context, bucketError);
  }

  // From here on, roll back the bucket if a later step fails so a retry isn't
  // blocked by a half-created project.
  const rollbackBucket = async () => {
    try {
      await removeBucket(bucketName, {
        config: await getStorageConfig(),
        force: true,
      });
    } catch {
      // best effort — surface the original error instead
    }
  };

  // 2. Create an access key scoped to this project.
  const { data: keyData, error: keyError } = await createAccessKey(
    `${bucketName}-key`,
    { config: await getIAMConfig(context) }
  );
  if (keyError || !keyData) {
    await rollbackBucket();
    failWithError(context, keyError ?? 'Failed to create access key');
  }

  // 3. Grant the key Editor access to the bucket.
  const { error: assignError } = await assignBucketRoles(
    keyData.id,
    [{ bucket: bucketName, role: 'Editor' }],
    { config: await getIAMConfig(context) }
  );
  if (assignError) {
    await rollbackBucket();
    failWithError(context, assignError);
  }

  // 4. Write the .env for @tigrisdata/storage.
  const endpoint = getTigrisConfig().endpoint;
  const envContents =
    [
      '# Generated by `tigris project setup`',
      `TIGRIS_STORAGE_ACCESS_KEY_ID=${keyData.id}`,
      `TIGRIS_STORAGE_SECRET_ACCESS_KEY=${keyData.secret}`,
      `TIGRIS_STORAGE_ENDPOINT=${endpoint}`,
      `TIGRIS_STORAGE_BUCKET=${bucketName}`,
    ].join('\n') + '\n';

  try {
    mkdirSync(dirname(envPath), { recursive: true });
    writeFileSync(envPath, envContents, { mode: 0o600 });
  } catch (err) {
    await rollbackBucket();
    return failWithError(context, err);
  }

  const isJson = format === 'json';

  // 5. Install the project's runtime npm packages (best-effort, non-fatal).
  const packages = skipInstall
    ? null
    : await installProjectPackages(process.cwd(), { quiet: isJson });

  // 6. Install agent resources for the project (best-effort, non-fatal).
  const agent = skipAgentSetup
    ? null
    : await setupAgentResources(process.cwd(), { quiet: isJson });

  if (isJson) {
    console.log(
      JSON.stringify({
        action: 'created',
        bucket: bucketName,
        accessKeyId: keyData.id,
        envFile: envPath,
        ...(packages ? { packages } : {}),
        ...(agent ? { agentSetup: agent } : {}),
      })
    );
  } else {
    console.log(`  Bucket:         ${bucketName}`);
    console.log(`  Access Key ID:  ${keyData.id}`);
    console.log(`  Env file:       ${envPath}`);
    console.log('');
    console.log(
      '  The secret access key was written to the .env file and will not be shown again.'
    );
    console.log('');
    if (packages) {
      console.log('');
      if (packages.error) {
        console.log(`  Package install skipped: ${packages.error}`);
      } else if (packages.installed.length > 0) {
        console.log(`  Installed ${packages.installed.join(', ')}.`);
      }
    }
    if (agent) {
      console.log('');
      if (agent.error) {
        console.log(`  Agent skill install skipped: ${agent.error}`);
      } else if (agent.installed.length > 0) {
        console.log(
          `  Installed ${agent.installed.length} Tigris skill(s) into .agents/skills (linked from .claude/skills).`
        );
        console.log(
          '  Please read the Tigris skills in .agents/skills to help the user decide how to integrate object storage into their application'
        );
      }
    }
  }

  printSuccess(context, { name: bucketName });
  printNextActions(context, { name: bucketName });
}
